import sys
import csv

input_file = sys.argv[1]
output_file = input_file.split('.')[0] + ".csv"

out_csv = []
data_header = []
data_header.append("Epoch")
data_header.append("Aggregate Average Bandwidth Channel 0 (GB/s)")
data_header.append("Rank 0 Reads")
data_header.append("Rank 0 Writes")
data_header.append("Bank 0 Bandwidth (GB/s)")
data_header.append("Bank 0 Latency (ns)")
data_header.append("Bank 1 Bandwidth (GB/s)")
data_header.append("Bank 1 Latency (ns)")
data_header.append("Bank 2 Bandwidth (GB/s)")
data_header.append("Bank 2 Latency (ns)")
data_header.append("Bank 3 Bandwidth (GB/s)")
data_header.append("Bank 3 Latency (ns)")
data_header.append("Bank 4 Bandwidth (GB/s)")
data_header.append("Bank 4 Latency (ns)")
data_header.append("Bank 5 Bandwidth (GB/s)")
data_header.append("Bank 5 Latency (ns)")
data_header.append("Bank 6 Bandwidth (GB/s)")
data_header.append("Bank 6 Latency (ns)")
data_header.append("Bank 7 Bandwidth (GB/s)")
data_header.append("Bank 7 Latency (ns)")
data_header.append("Bank 8 Bandwidth (GB/s)")
data_header.append("Bank 8 Latency (ns)")
data_header.append("Bank 9 Bandwidth (GB/s)")
data_header.append("Bank 9 Latency (ns)")
data_header.append("Bank 10 Bandwidth (GB/s)")
data_header.append("Bank 10 Latency (ns)")
data_header.append("Bank 11 Bandwidth (GB/s)")
data_header.append("Bank 11 Latency (ns)")
data_header.append("Bank 12 Bandwidth (GB/s)")
data_header.append("Bank 12 Latency (ns)")
data_header.append("Bank 13 Bandwidth (GB/s)")
data_header.append("Bank 13 Latency (ns)")
data_header.append("Bank 14 Bandwidth (GB/s)")
data_header.append("Bank 14 Latency (ns)")
data_header.append("Bank 15 Bandwidth (GB/s)")
data_header.append("Bank 15 Latency (ns)")
data_header.append("Average Power Rank 1 (W)")
data_header.append("Background (W)")
data_header.append("Act/Pre (W)")
data_header.append("Burst (W)")
data_header.append("Refresh (W)")
data_header.append("Rank 1 Reads")
data_header.append("Rank 1 Writes")
data_header.append("Bank 0 Bandwidth (GB/s)")
data_header.append("Bank 0 Latency (ns)")
data_header.append("Bank 1 Bandwidth (GB/s)")
data_header.append("Bank 1 Latency (ns)")
data_header.append("Bank 2 Bandwidth (GB/s)")
data_header.append("Bank 2 Latency (ns)")
data_header.append("Bank 3 Bandwidth (GB/s)")
data_header.append("Bank 3 Latency (ns)")
data_header.append("Bank 4 Bandwidth (GB/s)")
data_header.append("Bank 4 Latency (ns)")
data_header.append("Bank 5 Bandwidth (GB/s)")
data_header.append("Bank 5 Latency (ns)")
data_header.append("Bank 6 Bandwidth (GB/s)")
data_header.append("Bank 6 Latency (ns)")
data_header.append("Bank 7 Bandwidth (GB/s)")
data_header.append("Bank 7 Latency (ns)")
data_header.append("Bank 8 Bandwidth (GB/s)")
data_header.append("Bank 8 Latency (ns)")
data_header.append("Bank 9 Bandwidth (GB/s)")
data_header.append("Bank 9 Latency (ns)")
data_header.append("Bank 10 Bandwidth (GB/s)")
data_header.append("Bank 10 Latency (ns)")
data_header.append("Bank 11 Bandwidth (GB/s)")
data_header.append("Bank 11 Latency (ns)")
data_header.append("Bank 12 Bandwidth (GB/s)")
data_header.append("Bank 12 Latency (ns)")
data_header.append("Bank 13 Bandwidth (GB/s)")
data_header.append("Bank 13 Latency (ns)")
data_header.append("Bank 14 Bandwidth (GB/s)")
data_header.append("Bank 14 Latency (ns)")
data_header.append("Bank 15 Bandwidth (GB/s)")
data_header.append("Bank 15 Latency (ns)")
data_header.append("Average Power Rank 1 (W)")
data_header.append("Background (W)")
data_header.append("Act/Pre (W)")
data_header.append("Burst (W)")
data_header.append("Refresh (W)")
data_header.append("Rank 2 Reads")
data_header.append("Rank 2 Writes")
data_header.append("Bank 0 Bandwidth (GB/s)")
data_header.append("Bank 0 Latency (ns)")
data_header.append("Bank 1 Bandwidth (GB/s)")
data_header.append("Bank 1 Latency (ns)")
data_header.append("Bank 2 Bandwidth (GB/s)")
data_header.append("Bank 2 Latency (ns)")
data_header.append("Bank 3 Bandwidth (GB/s)")
data_header.append("Bank 3 Latency (ns)")
data_header.append("Bank 4 Bandwidth (GB/s)")
data_header.append("Bank 4 Latency (ns)")
data_header.append("Bank 5 Bandwidth (GB/s)")
data_header.append("Bank 5 Latency (ns)")
data_header.append("Bank 6 Bandwidth (GB/s)")
data_header.append("Bank 6 Latency (ns)")
data_header.append("Bank 7 Bandwidth (GB/s)")
data_header.append("Bank 7 Latency (ns)")
data_header.append("Bank 8 Bandwidth (GB/s)")
data_header.append("Bank 8 Latency (ns)")
data_header.append("Bank 9 Bandwidth (GB/s)")
data_header.append("Bank 9 Latency (ns)")
data_header.append("Bank 10 Bandwidth (GB/s)")
data_header.append("Bank 10 Latency (ns)")
data_header.append("Bank 11 Bandwidth (GB/s)")
data_header.append("Bank 11 Latency (ns)")
data_header.append("Bank 12 Bandwidth (GB/s)")
data_header.append("Bank 12 Latency (ns)")
data_header.append("Bank 13 Bandwidth (GB/s)")
data_header.append("Bank 13 Latency (ns)")
data_header.append("Bank 14 Bandwidth (GB/s)")
data_header.append("Bank 14 Latency (ns)")
data_header.append("Bank 15 Bandwidth (GB/s)")
data_header.append("Bank 15 Latency (ns)")
data_header.append("Average Power Rank 2 (W)")
data_header.append("Background (W)")
data_header.append("Act/Pre (W)")
data_header.append("Burst (W)")
data_header.append("Refresh (W)")
data_header.append("Rank 3 Reads")
data_header.append("Rank 3 Writes")
data_header.append("Bank 0 Bandwidth (GB/s)")
data_header.append("Bank 0 Latency (ns)")
data_header.append("Bank 1 Bandwidth (GB/s)")
data_header.append("Bank 1 Latency (ns)")
data_header.append("Bank 2 Bandwidth (GB/s)")
data_header.append("Bank 2 Latency (ns)")
data_header.append("Bank 3 Bandwidth (GB/s)")
data_header.append("Bank 3 Latency (ns)")
data_header.append("Bank 4 Bandwidth (GB/s)")
data_header.append("Bank 4 Latency (ns)")
data_header.append("Bank 5 Bandwidth (GB/s)")
data_header.append("Bank 5 Latency (ns)")
data_header.append("Bank 6 Bandwidth (GB/s)")
data_header.append("Bank 6 Latency (ns)")
data_header.append("Bank 7 Bandwidth (GB/s)")
data_header.append("Bank 7 Latency (ns)")
data_header.append("Bank 8 Bandwidth (GB/s)")
data_header.append("Bank 8 Latency (ns)")
data_header.append("Bank 9 Bandwidth (GB/s)")
data_header.append("Bank 9 Latency (ns)")
data_header.append("Bank 10 Bandwidth (GB/s)")
data_header.append("Bank 10 Latency (ns)")
data_header.append("Bank 11 Bandwidth (GB/s)")
data_header.append("Bank 11 Latency (ns)")
data_header.append("Bank 12 Bandwidth (GB/s)")
data_header.append("Bank 12 Latency (ns)")
data_header.append("Bank 13 Bandwidth (GB/s)")
data_header.append("Bank 13 Latency (ns)")
data_header.append("Bank 14 Bandwidth (GB/s)")
data_header.append("Bank 14 Latency (ns)")
data_header.append("Bank 15 Bandwidth (GB/s)")
data_header.append("Bank 15 Latency (ns)")
data_header.append("Average Power Rank 3 (W)")
data_header.append("Background (W)")
data_header.append("Act/Pre (W)")
data_header.append("Burst (W)")
data_header.append("Refresh (W)")
data_header.append("Aggregate Average Bandwidth Channel 1 (GB/s)")
data_header.append("Rank 0 Reads")
data_header.append("Rank 0 Writes")
data_header.append("Bank 0 Bandwidth (GB/s)")
data_header.append("Bank 0 Latency (ns)")
data_header.append("Bank 1 Bandwidth (GB/s)")
data_header.append("Bank 1 Latency (ns)")
data_header.append("Bank 2 Bandwidth (GB/s)")
data_header.append("Bank 2 Latency (ns)")
data_header.append("Bank 3 Bandwidth (GB/s)")
data_header.append("Bank 3 Latency (ns)")
data_header.append("Bank 4 Bandwidth (GB/s)")
data_header.append("Bank 4 Latency (ns)")
data_header.append("Bank 5 Bandwidth (GB/s)")
data_header.append("Bank 5 Latency (ns)")
data_header.append("Bank 6 Bandwidth (GB/s)")
data_header.append("Bank 6 Latency (ns)")
data_header.append("Bank 7 Bandwidth (GB/s)")
data_header.append("Bank 7 Latency (ns)")
data_header.append("Bank 8 Bandwidth (GB/s)")
data_header.append("Bank 8 Latency (ns)")
data_header.append("Bank 9 Bandwidth (GB/s)")
data_header.append("Bank 9 Latency (ns)")
data_header.append("Bank 10 Bandwidth (GB/s)")
data_header.append("Bank 10 Latency (ns)")
data_header.append("Bank 11 Bandwidth (GB/s)")
data_header.append("Bank 11 Latency (ns)")
data_header.append("Bank 12 Bandwidth (GB/s)")
data_header.append("Bank 12 Latency (ns)")
data_header.append("Bank 13 Bandwidth (GB/s)")
data_header.append("Bank 13 Latency (ns)")
data_header.append("Bank 14 Bandwidth (GB/s)")
data_header.append("Bank 14 Latency (ns)")
data_header.append("Bank 15 Bandwidth (GB/s)")
data_header.append("Bank 15 Latency (ns)")
data_header.append("Average Power Rank 0 (W)")
data_header.append("Background (W)")
data_header.append("Act/Pre (W)")
data_header.append("Burst (W)")
data_header.append("Refresh (W)")
data_header.append("Rank 1 Reads")
data_header.append("Rank 1 Writes")
data_header.append("Bank 0 Bandwidth (GB/s)")
data_header.append("Bank 0 Latency (ns)")
data_header.append("Bank 1 Bandwidth (GB/s)")
data_header.append("Bank 1 Latency (ns)")
data_header.append("Bank 2 Bandwidth (GB/s)")
data_header.append("Bank 2 Latency (ns)")
data_header.append("Bank 3 Bandwidth (GB/s)")
data_header.append("Bank 3 Latency (ns)")
data_header.append("Bank 4 Bandwidth (GB/s)")
data_header.append("Bank 4 Latency (ns)")
data_header.append("Bank 5 Bandwidth (GB/s)")
data_header.append("Bank 5 Latency (ns)")
data_header.append("Bank 6 Bandwidth (GB/s)")
data_header.append("Bank 6 Latency (ns)")
data_header.append("Bank 7 Bandwidth (GB/s)")
data_header.append("Bank 7 Latency (ns)")
data_header.append("Bank 8 Bandwidth (GB/s)")
data_header.append("Bank 8 Latency (ns)")
data_header.append("Bank 9 Bandwidth (GB/s)")
data_header.append("Bank 9 Latency (ns)")
data_header.append("Bank 10 Bandwidth (GB/s)")
data_header.append("Bank 10 Latency (ns)")
data_header.append("Bank 11 Bandwidth (GB/s)")
data_header.append("Bank 11 Latency (ns)")
data_header.append("Bank 12 Bandwidth (GB/s)")
data_header.append("Bank 12 Latency (ns)")
data_header.append("Bank 13 Bandwidth (GB/s)")
data_header.append("Bank 13 Latency (ns)")
data_header.append("Bank 14 Bandwidth (GB/s)")
data_header.append("Bank 14 Latency (ns)")
data_header.append("Bank 15 Bandwidth (GB/s)")
data_header.append("Bank 15 Latency (ns)")
data_header.append("Average Power Rank 1 (W)")
data_header.append("Background (W)")
data_header.append("Act/Pre (W)")
data_header.append("Burst (W)")
data_header.append("Refresh (W)")
data_header.append("Rank 2 Reads")
data_header.append("Rank 2 Writes")
data_header.append("Bank 0 Bandwidth (GB/s)")
data_header.append("Bank 0 Latency (ns)")
data_header.append("Bank 1 Bandwidth (GB/s)")
data_header.append("Bank 1 Latency (ns)")
data_header.append("Bank 2 Bandwidth (GB/s)")
data_header.append("Bank 2 Latency (ns)")
data_header.append("Bank 3 Bandwidth (GB/s)")
data_header.append("Bank 3 Latency (ns)")
data_header.append("Bank 4 Bandwidth (GB/s)")
data_header.append("Bank 4 Latency (ns)")
data_header.append("Bank 5 Bandwidth (GB/s)")
data_header.append("Bank 5 Latency (ns)")
data_header.append("Bank 6 Bandwidth (GB/s)")
data_header.append("Bank 6 Latency (ns)")
data_header.append("Bank 7 Bandwidth (GB/s)")
data_header.append("Bank 7 Latency (ns)")
data_header.append("Bank 8 Bandwidth (GB/s)")
data_header.append("Bank 8 Latency (ns)")
data_header.append("Bank 9 Bandwidth (GB/s)")
data_header.append("Bank 9 Latency (ns)")
data_header.append("Bank 10 Bandwidth (GB/s)")
data_header.append("Bank 10 Latency (ns)")
data_header.append("Bank 11 Bandwidth (GB/s)")
data_header.append("Bank 11 Latency (ns)")
data_header.append("Bank 12 Bandwidth (GB/s)")
data_header.append("Bank 12 Latency (ns)")
data_header.append("Bank 13 Bandwidth (GB/s)")
data_header.append("Bank 13 Latency (ns)")
data_header.append("Bank 14 Bandwidth (GB/s)")
data_header.append("Bank 14 Latency (ns)")
data_header.append("Bank 15 Bandwidth (GB/s)")
data_header.append("Bank 15 Latency (ns)")
data_header.append("Average Power Rank 2 (W)")
data_header.append("Background (W)")
data_header.append("Act/Pre (W)")
data_header.append("Burst (W)")
data_header.append("Refresh (W)")
data_header.append("Rank 3 Reads")
data_header.append("Rank 3 Writes")
data_header.append("Bank 0 Bandwidth (GB/s)")
data_header.append("Bank 0 Latency (ns)")
data_header.append("Bank 1 Bandwidth (GB/s)")
data_header.append("Bank 1 Latency (ns)")
data_header.append("Bank 2 Bandwidth (GB/s)")
data_header.append("Bank 2 Latency (ns)")
data_header.append("Bank 3 Bandwidth (GB/s)")
data_header.append("Bank 3 Latency (ns)")
data_header.append("Bank 4 Bandwidth (GB/s)")
data_header.append("Bank 4 Latency (ns)")
data_header.append("Bank 5 Bandwidth (GB/s)")
data_header.append("Bank 5 Latency (ns)")
data_header.append("Bank 6 Bandwidth (GB/s)")
data_header.append("Bank 6 Latency (ns)")
data_header.append("Bank 7 Bandwidth (GB/s)")
data_header.append("Bank 7 Latency (ns)")
data_header.append("Bank 8 Bandwidth (GB/s)")
data_header.append("Bank 8 Latency (ns)")
data_header.append("Bank 9 Bandwidth (GB/s)")
data_header.append("Bank 9 Latency (ns)")
data_header.append("Bank 10 Bandwidth (GB/s)")
data_header.append("Bank 10 Latency (ns)")
data_header.append("Bank 11 Bandwidth (GB/s)")
data_header.append("Bank 11 Latency (ns)")
data_header.append("Bank 12 Bandwidth (GB/s)")
data_header.append("Bank 12 Latency (ns)")
data_header.append("Bank 13 Bandwidth (GB/s)")
data_header.append("Bank 13 Latency (ns)")
data_header.append("Bank 14 Bandwidth (GB/s)")
data_header.append("Bank 14 Latency (ns)")
data_header.append("Bank 15 Bandwidth (GB/s)")
data_header.append("Bank 15 Latency (ns)")
data_header.append("Average Power Rank 3 (W)")
data_header.append("Background (W)")
data_header.append("Act/Pre (W)")
data_header.append("Burst (W)")
data_header.append("Refresh (W)")
data_header.append("Aggregate Average Bandwidth Channel 2 (GB/s)")
data_header.append("Rank 0 Reads")
data_header.append("Rank 0 Writes")
data_header.append("Bank 0 Bandwidth (GB/s)")
data_header.append("Bank 0 Latency (ns)")
data_header.append("Bank 1 Bandwidth (GB/s)")
data_header.append("Bank 1 Latency (ns)")
data_header.append("Bank 2 Bandwidth (GB/s)")
data_header.append("Bank 2 Latency (ns)")
data_header.append("Bank 3 Bandwidth (GB/s)")
data_header.append("Bank 3 Latency (ns)")
data_header.append("Bank 4 Bandwidth (GB/s)")
data_header.append("Bank 4 Latency (ns)")
data_header.append("Bank 5 Bandwidth (GB/s)")
data_header.append("Bank 5 Latency (ns)")
data_header.append("Bank 6 Bandwidth (GB/s)")
data_header.append("Bank 6 Latency (ns)")
data_header.append("Bank 7 Bandwidth (GB/s)")
data_header.append("Bank 7 Latency (ns)")
data_header.append("Bank 8 Bandwidth (GB/s)")
data_header.append("Bank 8 Latency (ns)")
data_header.append("Bank 9 Bandwidth (GB/s)")
data_header.append("Bank 9 Latency (ns)")
data_header.append("Bank 10 Bandwidth (GB/s)")
data_header.append("Bank 10 Latency (ns)")
data_header.append("Bank 11 Bandwidth (GB/s)")
data_header.append("Bank 11 Latency (ns)")
data_header.append("Bank 12 Bandwidth (GB/s)")
data_header.append("Bank 12 Latency (ns)")
data_header.append("Bank 13 Bandwidth (GB/s)")
data_header.append("Bank 13 Latency (ns)")
data_header.append("Bank 14 Bandwidth (GB/s)")
data_header.append("Bank 14 Latency (ns)")
data_header.append("Bank 15 Bandwidth (GB/s)")
data_header.append("Bank 15 Latency (ns)")
data_header.append("Average Power Rank 1 (W)")
data_header.append("Background (W)")
data_header.append("Act/Pre (W)")
data_header.append("Burst (W)")
data_header.append("Refresh (W)")
data_header.append("Rank 1 Reads")
data_header.append("Rank 1 Writes")
data_header.append("Bank 0 Bandwidth (GB/s)")
data_header.append("Bank 0 Latency (ns)")
data_header.append("Bank 1 Bandwidth (GB/s)")
data_header.append("Bank 1 Latency (ns)")
data_header.append("Bank 2 Bandwidth (GB/s)")
data_header.append("Bank 2 Latency (ns)")
data_header.append("Bank 3 Bandwidth (GB/s)")
data_header.append("Bank 3 Latency (ns)")
data_header.append("Bank 4 Bandwidth (GB/s)")
data_header.append("Bank 4 Latency (ns)")
data_header.append("Bank 5 Bandwidth (GB/s)")
data_header.append("Bank 5 Latency (ns)")
data_header.append("Bank 6 Bandwidth (GB/s)")
data_header.append("Bank 6 Latency (ns)")
data_header.append("Bank 7 Bandwidth (GB/s)")
data_header.append("Bank 7 Latency (ns)")
data_header.append("Bank 8 Bandwidth (GB/s)")
data_header.append("Bank 8 Latency (ns)")
data_header.append("Bank 9 Bandwidth (GB/s)")
data_header.append("Bank 9 Latency (ns)")
data_header.append("Bank 10 Bandwidth (GB/s)")
data_header.append("Bank 10 Latency (ns)")
data_header.append("Bank 11 Bandwidth (GB/s)")
data_header.append("Bank 11 Latency (ns)")
data_header.append("Bank 12 Bandwidth (GB/s)")
data_header.append("Bank 12 Latency (ns)")
data_header.append("Bank 13 Bandwidth (GB/s)")
data_header.append("Bank 13 Latency (ns)")
data_header.append("Bank 14 Bandwidth (GB/s)")
data_header.append("Bank 14 Latency (ns)")
data_header.append("Bank 15 Bandwidth (GB/s)")
data_header.append("Bank 15 Latency (ns)")
data_header.append("Average Power Rank 1 (W)")
data_header.append("Background (W)")
data_header.append("Act/Pre (W)")
data_header.append("Burst (W)")
data_header.append("Refresh (W)")
data_header.append("Rank 2 Reads")
data_header.append("Rank 2 Writes")
data_header.append("Bank 0 Bandwidth (GB/s)")
data_header.append("Bank 0 Latency (ns)")
data_header.append("Bank 1 Bandwidth (GB/s)")
data_header.append("Bank 1 Latency (ns)")
data_header.append("Bank 2 Bandwidth (GB/s)")
data_header.append("Bank 2 Latency (ns)")
data_header.append("Bank 3 Bandwidth (GB/s)")
data_header.append("Bank 3 Latency (ns)")
data_header.append("Bank 4 Bandwidth (GB/s)")
data_header.append("Bank 4 Latency (ns)")
data_header.append("Bank 5 Bandwidth (GB/s)")
data_header.append("Bank 5 Latency (ns)")
data_header.append("Bank 6 Bandwidth (GB/s)")
data_header.append("Bank 6 Latency (ns)")
data_header.append("Bank 7 Bandwidth (GB/s)")
data_header.append("Bank 7 Latency (ns)")
data_header.append("Bank 8 Bandwidth (GB/s)")
data_header.append("Bank 8 Latency (ns)")
data_header.append("Bank 9 Bandwidth (GB/s)")
data_header.append("Bank 9 Latency (ns)")
data_header.append("Bank 10 Bandwidth (GB/s)")
data_header.append("Bank 10 Latency (ns)")
data_header.append("Bank 11 Bandwidth (GB/s)")
data_header.append("Bank 11 Latency (ns)")
data_header.append("Bank 12 Bandwidth (GB/s)")
data_header.append("Bank 12 Latency (ns)")
data_header.append("Bank 13 Bandwidth (GB/s)")
data_header.append("Bank 13 Latency (ns)")
data_header.append("Bank 14 Bandwidth (GB/s)")
data_header.append("Bank 14 Latency (ns)")
data_header.append("Bank 15 Bandwidth (GB/s)")
data_header.append("Bank 15 Latency (ns)")
data_header.append("Average Power Rank 2 (W)")
data_header.append("Background (W)")
data_header.append("Act/Pre (W)")
data_header.append("Burst (W)")
data_header.append("Refresh (W)")
data_header.append("Rank 3 Reads")
data_header.append("Rank 3 Writes")
data_header.append("Bank 0 Bandwidth (GB/s)")
data_header.append("Bank 0 Latency (ns)")
data_header.append("Bank 1 Bandwidth (GB/s)")
data_header.append("Bank 1 Latency (ns)")
data_header.append("Bank 2 Bandwidth (GB/s)")
data_header.append("Bank 2 Latency (ns)")
data_header.append("Bank 3 Bandwidth (GB/s)")
data_header.append("Bank 3 Latency (ns)")
data_header.append("Bank 4 Bandwidth (GB/s)")
data_header.append("Bank 4 Latency (ns)")
data_header.append("Bank 5 Bandwidth (GB/s)")
data_header.append("Bank 5 Latency (ns)")
data_header.append("Bank 6 Bandwidth (GB/s)")
data_header.append("Bank 6 Latency (ns)")
data_header.append("Bank 7 Bandwidth (GB/s)")
data_header.append("Bank 7 Latency (ns)")
data_header.append("Bank 8 Bandwidth (GB/s)")
data_header.append("Bank 8 Latency (ns)")
data_header.append("Bank 9 Bandwidth (GB/s)")
data_header.append("Bank 9 Latency (ns)")
data_header.append("Bank 10 Bandwidth (GB/s)")
data_header.append("Bank 10 Latency (ns)")
data_header.append("Bank 11 Bandwidth (GB/s)")
data_header.append("Bank 11 Latency (ns)")
data_header.append("Bank 12 Bandwidth (GB/s)")
data_header.append("Bank 12 Latency (ns)")
data_header.append("Bank 13 Bandwidth (GB/s)")
data_header.append("Bank 13 Latency (ns)")
data_header.append("Bank 14 Bandwidth (GB/s)")
data_header.append("Bank 14 Latency (ns)")
data_header.append("Bank 15 Bandwidth (GB/s)")
data_header.append("Bank 15 Latency (ns)")
data_header.append("Average Power Rank 3 (W)")
data_header.append("Background (W)")
data_header.append("Act/Pre (W)")
data_header.append("Burst (W)")
data_header.append("Refresh (W)")
data_header.append("Aggregate Average Bandwidth Channel 3 (GB/s)")
data_header.append("Rank 0 Reads")
data_header.append("Rank 0 Writes")
data_header.append("Bank 0 Bandwidth (GB/s)")
data_header.append("Bank 0 Latency (ns)")
data_header.append("Bank 1 Bandwidth (GB/s)")
data_header.append("Bank 1 Latency (ns)")
data_header.append("Bank 2 Bandwidth (GB/s)")
data_header.append("Bank 2 Latency (ns)")
data_header.append("Bank 3 Bandwidth (GB/s)")
data_header.append("Bank 3 Latency (ns)")
data_header.append("Bank 4 Bandwidth (GB/s)")
data_header.append("Bank 4 Latency (ns)")
data_header.append("Bank 5 Bandwidth (GB/s)")
data_header.append("Bank 5 Latency (ns)")
data_header.append("Bank 6 Bandwidth (GB/s)")
data_header.append("Bank 6 Latency (ns)")
data_header.append("Bank 7 Bandwidth (GB/s)")
data_header.append("Bank 7 Latency (ns)")
data_header.append("Bank 8 Bandwidth (GB/s)")
data_header.append("Bank 8 Latency (ns)")
data_header.append("Bank 9 Bandwidth (GB/s)")
data_header.append("Bank 9 Latency (ns)")
data_header.append("Bank 10 Bandwidth (GB/s)")
data_header.append("Bank 10 Latency (ns)")
data_header.append("Bank 11 Bandwidth (GB/s)")
data_header.append("Bank 11 Latency (ns)")
data_header.append("Bank 12 Bandwidth (GB/s)")
data_header.append("Bank 12 Latency (ns)")
data_header.append("Bank 13 Bandwidth (GB/s)")
data_header.append("Bank 13 Latency (ns)")
data_header.append("Bank 14 Bandwidth (GB/s)")
data_header.append("Bank 14 Latency (ns)")
data_header.append("Bank 15 Bandwidth (GB/s)")
data_header.append("Bank 15 Latency (ns)")
data_header.append("Average Power Rank 0 (W)")
data_header.append("Background (W)")
data_header.append("Act/Pre (W)")
data_header.append("Burst (W)")
data_header.append("Refresh (W)")
data_header.append("Rank 1 Reads")
data_header.append("Rank 1 Writes")
data_header.append("Bank 0 Bandwidth (GB/s)")
data_header.append("Bank 0 Latency (ns)")
data_header.append("Bank 1 Bandwidth (GB/s)")
data_header.append("Bank 1 Latency (ns)")
data_header.append("Bank 2 Bandwidth (GB/s)")
data_header.append("Bank 2 Latency (ns)")
data_header.append("Bank 3 Bandwidth (GB/s)")
data_header.append("Bank 3 Latency (ns)")
data_header.append("Bank 4 Bandwidth (GB/s)")
data_header.append("Bank 4 Latency (ns)")
data_header.append("Bank 5 Bandwidth (GB/s)")
data_header.append("Bank 5 Latency (ns)")
data_header.append("Bank 6 Bandwidth (GB/s)")
data_header.append("Bank 6 Latency (ns)")
data_header.append("Bank 7 Bandwidth (GB/s)")
data_header.append("Bank 7 Latency (ns)")
data_header.append("Bank 8 Bandwidth (GB/s)")
data_header.append("Bank 8 Latency (ns)")
data_header.append("Bank 9 Bandwidth (GB/s)")
data_header.append("Bank 9 Latency (ns)")
data_header.append("Bank 10 Bandwidth (GB/s)")
data_header.append("Bank 10 Latency (ns)")
data_header.append("Bank 11 Bandwidth (GB/s)")
data_header.append("Bank 11 Latency (ns)")
data_header.append("Bank 12 Bandwidth (GB/s)")
data_header.append("Bank 12 Latency (ns)")
data_header.append("Bank 13 Bandwidth (GB/s)")
data_header.append("Bank 13 Latency (ns)")
data_header.append("Bank 14 Bandwidth (GB/s)")
data_header.append("Bank 14 Latency (ns)")
data_header.append("Bank 15 Bandwidth (GB/s)")
data_header.append("Bank 15 Latency (ns)")
data_header.append("Average Power Rank 1 (W)")
data_header.append("Background (W)")
data_header.append("Act/Pre (W)")
data_header.append("Burst (W)")
data_header.append("Refresh (W)")
data_header.append("Rank 2 Reads")
data_header.append("Rank 2 Writes")
data_header.append("Bank 0 Bandwidth (GB/s)")
data_header.append("Bank 0 Latency (ns)")
data_header.append("Bank 1 Bandwidth (GB/s)")
data_header.append("Bank 1 Latency (ns)")
data_header.append("Bank 2 Bandwidth (GB/s)")
data_header.append("Bank 2 Latency (ns)")
data_header.append("Bank 3 Bandwidth (GB/s)")
data_header.append("Bank 3 Latency (ns)")
data_header.append("Bank 4 Bandwidth (GB/s)")
data_header.append("Bank 4 Latency (ns)")
data_header.append("Bank 5 Bandwidth (GB/s)")
data_header.append("Bank 5 Latency (ns)")
data_header.append("Bank 6 Bandwidth (GB/s)")
data_header.append("Bank 6 Latency (ns)")
data_header.append("Bank 7 Bandwidth (GB/s)")
data_header.append("Bank 7 Latency (ns)")
data_header.append("Bank 8 Bandwidth (GB/s)")
data_header.append("Bank 8 Latency (ns)")
data_header.append("Bank 9 Bandwidth (GB/s)")
data_header.append("Bank 9 Latency (ns)")
data_header.append("Bank 10 Bandwidth (GB/s)")
data_header.append("Bank 10 Latency (ns)")
data_header.append("Bank 11 Bandwidth (GB/s)")
data_header.append("Bank 11 Latency (ns)")
data_header.append("Bank 12 Bandwidth (GB/s)")
data_header.append("Bank 12 Latency (ns)")
data_header.append("Bank 13 Bandwidth (GB/s)")
data_header.append("Bank 13 Latency (ns)")
data_header.append("Bank 14 Bandwidth (GB/s)")
data_header.append("Bank 14 Latency (ns)")
data_header.append("Bank 15 Bandwidth (GB/s)")
data_header.append("Bank 15 Latency (ns)")
data_header.append("Average Power Rank 2 (W)")
data_header.append("Background (W)")
data_header.append("Act/Pre (W)")
data_header.append("Burst (W)")
data_header.append("Refresh (W)")
data_header.append("Rank 3 Reads")
data_header.append("Rank 3 Writes")
data_header.append("Bank 0 Bandwidth (GB/s)")
data_header.append("Bank 0 Latency (ns)")
data_header.append("Bank 1 Bandwidth (GB/s)")
data_header.append("Bank 1 Latency (ns)")
data_header.append("Bank 2 Bandwidth (GB/s)")
data_header.append("Bank 2 Latency (ns)")
data_header.append("Bank 3 Bandwidth (GB/s)")
data_header.append("Bank 3 Latency (ns)")
data_header.append("Bank 4 Bandwidth (GB/s)")
data_header.append("Bank 4 Latency (ns)")
data_header.append("Bank 5 Bandwidth (GB/s)")
data_header.append("Bank 5 Latency (ns)")
data_header.append("Bank 6 Bandwidth (GB/s)")
data_header.append("Bank 6 Latency (ns)")
data_header.append("Bank 7 Bandwidth (GB/s)")
data_header.append("Bank 7 Latency (ns)")
data_header.append("Bank 8 Bandwidth (GB/s)")
data_header.append("Bank 8 Latency (ns)")
data_header.append("Bank 9 Bandwidth (GB/s)")
data_header.append("Bank 9 Latency (ns)")
data_header.append("Bank 10 Bandwidth (GB/s)")
data_header.append("Bank 10 Latency (ns)")
data_header.append("Bank 11 Bandwidth (GB/s)")
data_header.append("Bank 11 Latency (ns)")
data_header.append("Bank 12 Bandwidth (GB/s)")
data_header.append("Bank 12 Latency (ns)")
data_header.append("Bank 13 Bandwidth (GB/s)")
data_header.append("Bank 13 Latency (ns)")
data_header.append("Bank 14 Bandwidth (GB/s)")
data_header.append("Bank 14 Latency (ns)")
data_header.append("Bank 15 Bandwidth (GB/s)")
data_header.append("Bank 15 Latency (ns)")
data_header.append("Average Power Rank 3 (W)")
data_header.append("Background (W)")
data_header.append("Act/Pre (W)")
data_header.append("Burst (W)")
data_header.append("Refresh (W)")

with open(input_file, "r") as i_f, open(output_file, "w") as o_f:
  writer = csv.writer(o_f)
  writer.writerow(data_header)

  epoch = 0
  channel = -1
  rank = 0
  bank = 0
  csv_line = []
  csv_line.append(str(epoch))
  for line in i_f:
    split_line = line.strip().split(" ")
    if(split_line[0] == "======================================================="):
      channel+=1
      if(channel >= 4):
        channel = 0
        epoch+=1
        print(csv_line)
        writer.writerow(csv_line)
        csv_line = []
        csv_line.append(str(epoch))
    elif(split_line[0] == "Total"):
      csv_line.append(split_line[10].split("G")[0])
    elif(split_line[0] == "-Reads"):
      csv_line.append(split_line[3])
    elif(split_line[0] == "-Writes"):
      csv_line.append(split_line[2])
    elif(split_line[0] == "-Bandwidth"):
      csv_line.append(split_line[6])
      temp = split_line[7].split("\t")[-1]
      if temp == "-nan":
        temp = ""
      csv_line.append(temp)
    elif(split_line[0] == "Average"):
      csv_line.append(split_line[8])
    elif(split_line[0] == "-Background"):
      csv_line.append(split_line[7])
    elif(split_line[0] == "-Act/Pre"):
      csv_line.append(split_line[10])
    elif(split_line[0] == "-Burst"):
      csv_line.append(split_line[12])
    elif(split_line[0] == "-Refresh"):
      csv_line.append(split_line[10])
